CREATE TABLE provinces (
    id             BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(2)    NOT NULL,
    name_th        VARCHAR(150)  NOT NULL,
    name_en        VARCHAR(150),
    order_position INT           NOT NULL DEFAULT 0,
    active_flag    BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ   NOT NULL,
    created_by     VARCHAR(100)  NOT NULL,
    updated_at     TIMESTAMPTZ   NOT NULL,
    updated_by     VARCHAR(100)  NOT NULL,
    version        BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uq_provinces_code UNIQUE (code)
);

COMMENT ON TABLE provinces IS 'ข้อมูลอ้างอิงจังหวัด — code ใช้รหัสมาตรฐานกรมการปกครอง (DOPA) 2 หลัก — ยังไม่มี seed data จริง รอ import dataset ราชการ 77 จังหวัด แยกเป็นงานต่างหาก';
