CREATE TABLE car_powertrain_types (
    id             BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(20)   NOT NULL,
    name_th        VARCHAR(100)  NOT NULL,
    name_en        VARCHAR(100),
    order_position INT           NOT NULL DEFAULT 0,
    active_flag    BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ   NOT NULL,
    created_by     VARCHAR(100)  NOT NULL,
    updated_at     TIMESTAMPTZ   NOT NULL,
    updated_by     VARCHAR(100)  NOT NULL,
    version        BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uq_car_powertrain_types_code UNIQUE (code)
);

COMMENT ON TABLE car_powertrain_types IS 'ข้อมูลอ้างอิงประเภทระบบขับเคลื่อน — ตรงกับ legacy master.CarPowerType ที่อ้างอิงจาก CarModel.power_type_id แต่ไฟล์ export ที่ได้รับไม่มีข้อมูลตารางนี้ (export เฉพาะโดเมน Package) — ยังไม่มี seed data จริง รอรายการจากธุรกิจหรือ export เพิ่มจากระบบเดิม';
