CREATE TABLE car_countries (
    id             BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(10)   NOT NULL,
    name_th        VARCHAR(100)  NOT NULL,
    name_en        VARCHAR(100),
    order_position INT           NOT NULL DEFAULT 0,
    active_flag    BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ   NOT NULL,
    created_by     VARCHAR(100)  NOT NULL,
    updated_at     TIMESTAMPTZ   NOT NULL,
    updated_by     VARCHAR(100)  NOT NULL,
    version        BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uq_car_countries_code UNIQUE (code)
);

COMMENT ON TABLE car_countries IS 'ข้อมูลอ้างอิงประเทศผู้ผลิตรถ ใช้เฉพาะโดเมนรถ — ยังไม่มี seed data จริง รอรายการจากธุรกิจ';
