-- seed จากข้อมูลจริง legacy master.Occupation (27 แถว)
INSERT INTO occupations (code, name_th, name_en, order_position, active_flag, created_at, created_by, updated_at, updated_by)
VALUES
    ('01', 'ผู้บริหารระดับสูง', 'Senior Executives', 1, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('02', 'ผู้บริหารระดับกลาง', 'Middle Management', 2, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('03', 'ข้าราชการ / พนง.รัฐวิสาหกิจ', 'Civil Servant / State Enterprise Staff', 3, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('04', 'ข้าราชการตำรวจ / ทหาร', 'Police / Military', 4, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('05', 'นักการเมือง', 'Politician', 5, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('06', 'แพทย์', 'Doctors / Physician', 6, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('07', 'พยาบาล / อาชีพที่เกี่ยวกับ การรักษาพยาบาล', 'Nurse / Other Medical and Health-related Professions', 7, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('08', 'วิศวกร / ช่างเทคนิค', 'Engineer / Technician', 8, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('09', 'สถาปนิก / นักออกแบบ / ช่างศิลป์ / ศิลปิน', 'Architect / Designer / Artists', 9, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('10', 'นักแสดง / นักร้อง / อาชีพที่เกี่ยวกับธุรกิจบันเทิง', 'Actors / Singers / Enter-tainment', 10, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('11', 'พนง.ขาย / ตลาดที่ต้องออกตลาด', 'Outdoor Sales / Marketing person', 11, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('12', 'เจ้าของกิจการ', 'Business Owner', 12, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('13', 'เร่ขายของด้วยรถ', 'Self-employed Trades-vehicle', 13, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('14', 'อาชีพอิสระ / ผู้รับเหมา / ที่ปรึกษา', 'Freelance / Contractors /  Consultant', 14, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('15', 'คนขับรถ', 'Chauffeur / Driver', 15, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('16', 'เกษตรกร', 'Farmers', 16, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('17', 'แม่บ้าน', 'Housewife', 17, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('18', 'นักข่าวและช่างภาพทำข่าว', 'Outdoor Journalist / Media photographer', 18, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('19', 'ครู / อาจารย์ / นักการศึกษา', 'Teacher and All Educators', 19, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('20', 'พนักงานบัญชี / การเงิน', 'Accountant / Cashier', 20, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('21', 'จนท.ธุรการ / เลขาฯ / เสมียน /', 'Admin. / Secretary / Clerk / Service Personnel', 21, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('22', 'ไม่ได้ทำงานใดๆ', 'Unemployed', 22, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('23', 'พนักงานส่งของ', NULL, 23, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('91', 'ธุรกิจรถเช่า', NULL, 24, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('92', 'ธุรกิจโลจิสติกส์', NULL, 25, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('93', 'ธุรกิจขนส่งวัตถุอันตราย', NULL, 26, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('99', 'อื่นๆ', 'Other', 27, TRUE, now(), 'SYSTEM', now(), 'SYSTEM');
