-- legacy master.LicenseProvince มี province_id (FK จริงไป province) และ license_province_risc_id
-- (external ID crosswalk สำหรับส่งรายงานให้ RISC) — เพิ่ม column เก็บไว้
ALTER TABLE car_license_provinces ADD COLUMN province_id UUID REFERENCES provinces(id);
ALTER TABLE car_license_provinces ADD COLUMN risc_code VARCHAR(20);

CREATE INDEX idx_car_license_provinces_province_id ON car_license_provinces(province_id);

-- seed จากข้อมูลจริง legacy master.LicenseProvince (82 แถว)
INSERT INTO car_license_provinces (code, name_th, name_en, risc_code, province_id, order_position, active_flag, created_at, created_by, updated_at, updated_by)
VALUES
    ('กท', 'กรุงเทพมหานคร', 'BANGKOK', 'C01', (SELECT id FROM provinces WHERE code = '10'), 1, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สป', 'สมุทรปราการ', 'SAMUT PRAKAN ', 'E08', (SELECT id FROM provinces WHERE code = '11'), 60, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('นบ', 'นนทบุรี', 'NONTHABURI', 'C04', (SELECT id FROM provinces WHERE code = '12'), 24, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ปท', 'ปทุมธานี', 'PATHUM THANI ', 'C03', (SELECT id FROM provinces WHERE code = '13'), 29, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('อย', 'พระนครศรีอยุธยา', 'PHRA NAKHON SI AYUTTHAYA ', 'C05', (SELECT id FROM provinces WHERE code = '14'), 33, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('อท', 'อ่างทอง', 'ANG THONG ', 'C13', (SELECT id FROM provinces WHERE code = '15'), 72, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ลบ', 'ลพบุรี', 'LOP BURI ', 'C07', (SELECT id FROM provinces WHERE code = '16'), 52, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สห', 'สิงห์บุรี', 'SING BURI ', 'C15', (SELECT id FROM provinces WHERE code = '17'), 65, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ชน', 'ชัยนาท', 'CHAI NAT ', 'C14', (SELECT id FROM provinces WHERE code = '18'), 10, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สบ', 'สระบุรี', 'SARABURI ', 'C08', (SELECT id FROM provinces WHERE code = '19'), 64, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ชบ', 'ชลบุรี', 'CHON BURI ', 'E04', (SELECT id FROM provinces WHERE code = '20'), 9, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('รย', 'ระยอง', 'RAYONG', 'E05', (SELECT id FROM provinces WHERE code = '21'), 50, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('จบ', 'จันทบุรี', 'CHANTHABURI', 'E06', (SELECT id FROM provinces WHERE code = '22'), 7, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ตร', 'ตราด', 'TRAT ', 'E07', (SELECT id FROM provinces WHERE code = '23'), 16, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ฉช', 'ฉะเชิงเทรา', 'CHACHOENGSAO', 'E03', (SELECT id FROM provinces WHERE code = '24'), 8, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ปจ', 'ปราจีนบุรี', 'PRACHIN BURI ', 'E01', (SELECT id FROM provinces WHERE code = '25'), 31, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('นย', 'นครนายก', 'NAKHON NAYOK ', 'E02', (SELECT id FROM provinces WHERE code = '26'), 18, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สก', 'สระแก้ว', 'SA KAEO', 'C16', (SELECT id FROM provinces WHERE code = '27'), 63, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('นม', 'นครราชสีมา', 'NAKHON RATCHASIMA ', 'D07', (SELECT id FROM provinces WHERE code = '30'), 21, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('บร', 'บุรีรัมย์', 'BURI RAM ', 'D13', (SELECT id FROM provinces WHERE code = '31'), 28, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สร', 'สุรินทร์', 'SURIN', 'D11', (SELECT id FROM provinces WHERE code = '32'), 69, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ศก', 'ศรีสะเกษ', 'SI SA KET ', 'D12', (SELECT id FROM provinces WHERE code = '33'), 56, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('อบ', 'อุบลราชธานี', 'UBON RATCHATHANI ', 'D14', (SELECT id FROM provinces WHERE code = '34'), 77, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ยส', 'ยโสธร', 'YASOTHON', 'D16', (SELECT id FROM provinces WHERE code = '35'), 46, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ชย', 'ชัยภูมิ', 'CHAIYAPHUM', 'D08', (SELECT id FROM provinces WHERE code = '36'), 11, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('อจ', 'อำนาจเจริญ', 'AMNAT CHAROEN ', 'D19', (SELECT id FROM provinces WHERE code = '37'), 73, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('บก', 'บึงกาฬ', 'BUENG KAN ', 'D20', (SELECT id FROM provinces WHERE code = '38'), 27, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('นภ', 'หนองบัวลำภู', 'NONG BUA LAM PHU ', 'D18', (SELECT id FROM provinces WHERE code = '39'), 71, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ขก', 'ขอนแก่น', 'KHON KAEN ', 'D05', (SELECT id FROM provinces WHERE code = '40'), 6, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('อด', 'อุดรธานี', 'UDON THANI ', 'D06', (SELECT id FROM provinces WHERE code = '41'), 74, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ลย', 'เลย', 'LOEI', 'D02', (SELECT id FROM provinces WHERE code = '42'), 55, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('นค', 'หนองคาย', 'NONG KHAI ', 'D01', (SELECT id FROM provinces WHERE code = '43'), 70, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('มค', 'มหาสารคาม', 'MAHA SARAKHAM ', 'D10', (SELECT id FROM provinces WHERE code = '44'), 43, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('รอ', 'ร้อยเอ็ด', 'ROI ET ', 'D09', (SELECT id FROM provinces WHERE code = '45'), 48, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('กส', 'กาฬสินธุ์', 'KALASIN', 'D15', (SELECT id FROM provinces WHERE code = '46'), 4, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สน', 'สกลนคร', 'SAKON NAKHON ', 'D04', (SELECT id FROM provinces WHERE code = '47'), 57, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('นพ', 'นครพนม', 'NAKHON PHANOM ', 'D03', (SELECT id FROM provinces WHERE code = '48'), 20, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('มห', 'มุกดาหาร', 'MUKDAHAN', 'D17', (SELECT id FROM provinces WHERE code = '49'), 44, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ชม', 'เชียงใหม่', 'CHIANG MAI ', 'N03', (SELECT id FROM provinces WHERE code = '50'), 14, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ลพ', 'ลำพูน', 'LAMPHUN', 'N04', (SELECT id FROM provinces WHERE code = '51'), 54, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ลป', 'ลำปาง', 'LAMPANG', 'N05', (SELECT id FROM provinces WHERE code = '52'), 53, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('อต', 'อุตรดิตถ์', 'UTTARADIT', 'N11', (SELECT id FROM provinces WHERE code = '53'), 75, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('พร', 'แพร่', 'PHRAE', 'N06', (SELECT id FROM provinces WHERE code = '54'), 41, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('นน', 'น่าน', 'NAN', 'N07', (SELECT id FROM provinces WHERE code = '55'), 26, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('พย', 'พะเยา', 'PHAYAO', 'N17', (SELECT id FROM provinces WHERE code = '56'), 34, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ชร', 'เชียงราย', 'CHIANG RAI ', 'N01', (SELECT id FROM provinces WHERE code = '57'), 13, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('มส', 'แม่ฮ่องสอน', 'MAE HONG SON ', 'N18', (SELECT id FROM provinces WHERE code = '58'), 45, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('นว', 'นครสวรรค์', 'NAKHON SAWAN ', 'N14', (SELECT id FROM provinces WHERE code = '60'), 23, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('อน', 'อุทัยธานี', 'UTHAI THANI ', 'N15', (SELECT id FROM provinces WHERE code = '61'), 76, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('กพ', 'กำแพงเพชร', 'KAMPHAENG PHET ', 'N13', (SELECT id FROM provinces WHERE code = '62'), 5, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ตก', 'ตาก', 'TAK', 'N10', (SELECT id FROM provinces WHERE code = '63'), 17, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สท', 'สุโขทัย', 'SUKHOTHAI', 'N09', (SELECT id FROM provinces WHERE code = '64'), 66, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('พล', 'พิษณุโลก', 'PHITSANULOK', 'N08', (SELECT id FROM provinces WHERE code = '65'), 38, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('พจ', 'พิจิตร', 'PHICHIT', 'N12', (SELECT id FROM provinces WHERE code = '66'), 37, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('พช', 'เพชรบูรณ์', 'PHETCHABUN', 'N16', (SELECT id FROM provinces WHERE code = '67'), 40, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('รบ', 'ราชบุรี', 'RATCHABURI', 'C10', (SELECT id FROM provinces WHERE code = '70'), 51, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('กจ', 'กาญจนบุรี', 'KANCHANABURI ', 'C09', (SELECT id FROM provinces WHERE code = '71'), 3, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สพ', 'สุพรรณบุรี', 'SUPHAN BURI ', 'C12', (SELECT id FROM provinces WHERE code = '72'), 67, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('นฐ', 'นครปฐม', 'NAKHON PATHOM ', 'C06', (SELECT id FROM provinces WHERE code = '73'), 19, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สค', 'สมุทรสาคร', 'SAMUT SAKHON ', 'E09', (SELECT id FROM provinces WHERE code = '74'), 62, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สส', 'สมุทรสงคราม', 'SAMUT SONGKHRAM ', 'E10', (SELECT id FROM provinces WHERE code = '75'), 61, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('พบ', 'เพชรบุรี', 'PHETCHABURI', 'C11', (SELECT id FROM provinces WHERE code = '76'), 39, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ปข', 'ประจวบคีรีขันธ์', 'PRACHUAP KHIRI KHAN ', 'S15', (SELECT id FROM provinces WHERE code = '77'), 30, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('นศ', 'นครศรีธรรมราช', 'NAKHON SI THAMMARAT ', 'S06', (SELECT id FROM provinces WHERE code = '80'), 22, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('กบ', 'กระบี่', 'KRABI', 'S07', (SELECT id FROM provinces WHERE code = '81'), 2, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('พง', 'พังงา', 'PHANGNGA', 'S04', (SELECT id FROM provinces WHERE code = '82'), 35, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ภก', 'ภูเก็ต', 'PHUKET', 'S05', (SELECT id FROM provinces WHERE code = '83'), 42, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สฎ', 'สุราษฎร์ธานี', 'SURAT THANI ', 'S02', (SELECT id FROM provinces WHERE code = '84'), 68, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('รน', 'ระนอง', 'RANONG', 'S03', (SELECT id FROM provinces WHERE code = '85'), 49, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ชพ', 'ชุมพร', 'CHUMPHON', 'S01', (SELECT id FROM provinces WHERE code = '86'), 12, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สข', 'สงขลา', 'SONGKHLA', 'S09', (SELECT id FROM provinces WHERE code = '90'), 58, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('สต', 'สตูล', 'SATUN', 'S11', (SELECT id FROM provinces WHERE code = '91'), 59, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ตง', 'ตรัง', 'TRANG', 'S10', (SELECT id FROM provinces WHERE code = '92'), 15, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('พท', 'พัทลุง', 'PHATTHALUNG', 'S08', (SELECT id FROM provinces WHERE code = '93'), 36, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ปน', 'ปัตตานี', 'PATTANI', 'S12', (SELECT id FROM provinces WHERE code = '94'), 32, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ยล', 'ยะลา', 'YALA', 'S13', (SELECT id FROM provinces WHERE code = '95'), 47, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('นธ', 'นราธิวาส', 'NARATHIWAT', 'S14', (SELECT id FROM provinces WHERE code = '96'), 25, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('บต', 'เบตง', 'Betong', '78', (SELECT id FROM provinces WHERE code = '95'), 78, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ปด', 'ป้ายแดง', 'Temporary Plate', '79', NULL, 79, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('นท', 'ไม่มีทะเบียน', 'Unregistered', '80', NULL, 80, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('รช', 'รถราชการ', 'Government Plate', '81', NULL, 81, TRUE, now(), 'SYSTEM', now(), 'SYSTEM'),
    ('ตป', 'ต่างประเทศ', 'Foreign Plate', '82', NULL, 82, TRUE, now(), 'SYSTEM', now(), 'SYSTEM');
